### ISSUE TITLE
[feature request] Parameterize resources

### ISSUE THREAD

**Issue by virgilp** [extremeandy/AsyncResourcePool#5]
When using the async resource pool, sometimes the resources are not quite equivalent - e.g. for the Snowflake example, you may want to run queries on a specific database, using a specific warehouse. You could have dedicated resource pools per <db, warehouse> pair, but it kinda defeats the purpose. Also - it's much cheaper to change the DB (or the warehouse) than to open a new connection.

We should have a way to get a parameterized resource  - i.e. get one resource from the pool that best matches the parameters requested, and if none is found, just get one & change parameters to the requested values (e.g. by invoking "ChangeDatabase()" on the connection. 

(interested in having this if I develop it? Some requirements for accepting such submission?)

**Comment by extremeandy** [comment]
I can definitely understand the need for parameterize resources, and I've had to implement that myself, but I don't think that pushing that logic inside `AsyncResourcePool` is the best solution.

You would need to then partition your pool by whatever you're keying your resources on. But that would need to be dynamic based on the number of keys, which can't really be known upfront. So say you had a max of 100 resources and for a while you were only accessing 1 key, and you had 100 resources sitting there related to that 1 key. Then you start creating resources using a 2nd key - what should we do with the 100 resources that already exist? Delete 50 of them and reserve 50 slots for the 2nd key? And so on. It just gets really murky around deciding which resources to maintain for which keys.

I would suggest creating a wrapper which contains multiple connection pools and managing them in the wrapper.

If you know up-front the cardinality of keys, you could compute the max resources for each pool up-front as well. E.g. suppose you wanted a global limit of 100 connections to Snowflake regardless of db/warehouse, and you know you have 4 combinations of db/warehouse, then you could create 4 connection pools with max 25 connections per pool.

If you want to come up with fancier logic (e. g. dynamically resizing pools based on key universe) then you can still do it, but that logic can sit in the wrapper. If a change is needed in `AsyncResourcePool` to facilitate resizing pools then I think that definitely makes sense.

Thoughts?

**Comment by virgilp** [comment]
(just a top-level clarification: this discussion only makes sense if changing a resource parameter is much cheaper than destroying a resource & opening a new one with a different parameter)

>  If a change is needed in AsyncResourcePool to facilitate resizing pools then I think that definitely makes sense.
> Thoughts?

Hmmm... maybe the logic can sit in a wrapper if we facilitate transferring resources between pools. Would that be a better change/ one that you would support? Scenario: say I have just 2 warehouses, but the usage pattern is widely different (one is mostly used at day, the other mostly used at night). I want to be able to transfer connections from one pool to another using the external wrapper (instead of resizing one pool down and another pool up, to do "USE WAREHOUSE" and move connection).  

OTOH, this might be more complicated overall than adding this management inside the resource pool; I think it'd make sense to have it in the pool, for the particular case of resources that have cheap methods of changing parameters. To your comment of "it just gets really murky" - I was thinking of a simple strategy first: say we only support one parameter. If we have a free resource that matches desired parameter, you return it. Otherwise, return a resource of the least-recently-used type & change the parameter value.

**Comment by extremeandy** [comment]
Sorry I'm having a little difficulty understanding the use case. It seems unlikely that it's possible to change the connection string for a connection that is already open? Normally I'd think things that are expensive to create like connections can't be changed on the fly.

In terms of moving resources from one pool to another, we could add a method `TryRemove` which would allow you to check for an existing resource and remove it from the pool, to do whatever you wish with it.

**Comment by virgilp** [comment]
One can't arbitrarily change the connection string but some things are possible. To change the warehouse Its just one statement, `USE WAREHOUSE other_wh`

**Comment by extremeandy** [comment]
> One can't arbitrarily change the connection string but some things are possible. To change the warehouse one just needs to execute one SQL statement on that connection, USE WAREHOUSE other_wh (that changes the default warehouse for the session, and the session is associated with the connection)..

Gotcha.

> OTOH, this might be more complicated overall than adding this management inside the resource pool; I think it'd make sense to have it in the pool, for the particular case of resources that have cheap methods of changing parameters. To your comment of "it just gets really murky" - I was thinking of a simple strategy first: say we only support one parameter. If we have a free resource that matches desired parameter, return it. Otherwise, return a resource of the least-recently-used type & change the parameter value. If no resource is available and we can increase the pool size, create new resource of desired type.

I still think it's too specific a use-case to implement in a generic class like `AsyncResourcePool`, but I do think it would make sense for us to add some overloads which would facilitate creating a wrapper with your specific logic.

If we add two overloads:
* A synchronous method `TryGet` which will return immediately with `true` if there already exists an available resource, and and `out T` with the resource, or `false` if no resource is available
* A synchronous method `TryRemove` which is the same as `TryGet` but removes the resource from the pool if found
* A synchronous method `Add` which allows a resource to be added to a pool

In your wrapper:
* Maintain a `Dictionary<string, ConnectionPool>` where the key is the warehouse name
* When trying to get/create a connection for e.g. warehouse with name `"WH1"`:
  1. First look up the connection pool for `"WH1"` from the `Dictionary`, and use `TryGet`. If it returns `true`, use the connection. If it returns `false`, continue to (ii).
  2. Loop over all other connection pools and use `TryRemove` to remove a connection from one of the other pools. If none is found, then continue to (iii). If one is found, then execute `USE WAREHOUSE WH1` on that connection, then use it. Once done, use `Add` to add it to the pool that corresponds to `"WH1"`.
  3. Fall back to using `Get` on the connection pool that corresponds to `"WH1"`.

What do you reckon?

**Comment by virgilp** [comment]
Yes, this works.

**Comment by extremeandy** [comment]
Wanna cast your eye over this? https://github.com/extremeandy/AsyncResourcePool/pull/6

Not sure if I need to add you as a reviewer for you to comment there, let me know

**Comment by extremeandy** [comment]
Would you also want the ability to change the size of the pool on the fly? E.g. if overnight you don't need to maintain as many active connections on one warehouse you might want to lower the minimum to `0` so that resources aren't unnecessarily being maintained?
